// import Image from "next/image";
import { Suspense } from "react";
import Spinner from "../../../../projects/loading";
import { blog } from "@/services/blog";
import Image from "next/image";
import { TBlogDetails } from "@/types/blog.";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Ahosanul Islam | Blogs | Blog Details",
  description: "Generated by create next app",
};
export default async function BlogDetailsPage({
  params,
}: {
  params: Promise<{ category: string; slug: string; blogId: string }>;
}) {
  const { blogId } = await params;
  const blogData = await blog.getSingleBlog(blogId);
  const blogDetails: TBlogDetails = blogData.data;

  return (
    <Suspense fallback={<Spinner />}>
      <div className="max-w-4xl mx-auto p-6">
        <h1 className="text-5xl text-gray-300  font-bold">
          {blogDetails.titleId.title}
        </h1>
        {blogDetails && blogDetails.coverImage && (
          <Image
            className="w-full h-64 object-cover rounded-lg mt-4"
            src={blogDetails.coverImage}
            height={400}
            width={800}
            alt={blogDetails.titleId.title}
          />
        )}
        <p className="text-gray-400 mt-4 text-justify">
          {blogDetails.shortDescription}
        </p>

        <div
          dangerouslySetInnerHTML={{ __html: blogDetails.contentId.content }}
        />
      </div>
    </Suspense>
  );
}
