import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

import Providers from "@/lib/providers";
import BlogLeftSidebar from "@/components/blog/layout/BlogLeftSidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ahosanul Islam | Blogs",
  description: "Generated by create next app",
};

export default function BlogLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <div
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full mx-auto `}
      >
        <div className="w-full flex gap-8 min-h-screen">
          <aside className="w-1/4">
            <BlogLeftSidebar />
          </aside>
          <aside className="w-3/4 ">{children}</aside>
        </div>
      </div>
    </Providers>
  );
}
