import Projects from "@/components/projects/Projects";
import { getAllProjects } from "@/lib/providers/dataFetch/projects";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Ahosanul Islam | Projects",
  description: "Generated by create next app",
};
export default async function ProjectPage() {
  const { data: projects } = await getAllProjects();

  return <Projects projects={projects} />;
}
