import Projects from "@/components/projects/Projects";
import { project } from "@/services/project";

import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Ahosanul Islam | Projects",
  description: "Generated by create next app",
};
export default async function ProjectPage() {
  const projects = await project.getAllProjects();
  console.log(project);
  return (
    <Projects projects={Array.isArray(projects.data) ? projects.data : []} />
  );
}
